services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    hostname: 2a5-app-development
    ports:
      - "3001:3001"
    container_name: 2a5-app-development
    environment:
      - DOCKER_API_HOSTNAME=2a5-api-development
      - DOCKER_API_PORT=3000
    networks:
      - 2a5-extern
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./components
          target: /app/components
        - action: sync
          path: ./lib
          target: /app/lib
        - action: sync
          path: ./pages
          target: /app/pages
        - action: sync
          path: ./public
          target: /app/public
        - action: sync
          path: ./styles
          target: /app/styles
        - action: rebuild
          path: package.json

networks:
  2a5-extern:
    name: 2a5
    external: true